name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - master  # Runs the workflow when code is pushed to the main branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven

      - name: Build the Spring Boot Application
        run: mvn clean package

      - name: Run the Spring Boot Application
        run: |
          nohup java -jar target/*.jar --server.port=8080 --server.address=0.0.0.0 &
